<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Catalogo UrbanWear: streetwear essenziale.">
    <title>Catalogo — UrbanWear</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#0a0a0a] font-sans text-zinc-100 antialiased">
    <div class="border-b border-white/10 bg-[#b6ff33] px-4 py-2 text-center text-[10px] font-black tracking-[0.2em] text-black sm:text-xs">SPEDIZIONE GRATUITA IN ITALIA SOPRA I 100 €</div>
    <header class="border-b border-white/10 bg-[#0a0a0a]/90 backdrop-blur">
        <nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8" aria-label="Navigazione principale">
            <a href="{{ route('home') }}" class="text-xl font-black tracking-[-0.08em] text-white sm:text-2xl">URBAN<span class="text-[#b6ff33]">WEAR</span></a>
            <div class="hidden items-center gap-8 text-xs font-bold uppercase tracking-[0.16em] text-zinc-300 lg:flex"><a class="transition hover:text-[#b6ff33]" href="{{ route('home') }}#drop">Nuovi arrivi</a><a class="text-[#b6ff33]" href="{{ route('catalog.index') }}">Shop</a><a class="transition hover:text-[#b6ff33]" href="{{ route('home') }}#story">Manifesto</a></div>
            <a class="relative text-zinc-300 transition hover:text-[#b6ff33]" href="{{ route('cart.index') }}" aria-label="Apri il carrello"><svg class="size-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3h2l2.4 12.1a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L21 7H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg><span class="absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-[#b6ff33] text-[9px] font-black text-black">{{ collect(session('cart', []))->sum('quantity') }}</span></a>
        </nav>
    </header>
    <main class="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16">
        <div class="border-b border-white/10 pb-10"><p class="text-[10px] font-black uppercase tracking-[0.24em] text-[#b6ff33]">UrbanWear / Shop</p><h1 class="mt-3 text-5xl font-black tracking-[-0.07em] text-white sm:text-7xl">IL CATALOGO.</h1><p class="mt-4 max-w-lg text-sm leading-7 text-zinc-400">Capi essenziali costruiti per la città. Trova la tua uniforme.</p></div>
        <div class="grid gap-10 py-10 lg:grid-cols-[260px_1fr]">
            <aside>
                <form method="GET" action="{{ route('catalog.index') }}" class="space-y-8 lg:sticky lg:top-6">
                    <div><label class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400" for="search">Cerca</label><div class="mt-3 flex border-b border-white/20 focus-within:border-[#b6ff33]"><input id="search" name="search" value="{{ request('search') }}" class="w-full bg-transparent py-3 text-sm text-white placeholder:text-zinc-600 focus:outline-none" placeholder="Nome o codice prodotto"><svg class="my-auto size-4 text-zinc-500" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4.2-4.2"/></svg></div></div>
                    <fieldset><legend class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400">Categoria</legend><div class="mt-3 space-y-3">@foreach ($categories as $category)<label class="flex cursor-pointer items-center gap-3 text-sm text-zinc-300"><input class="size-4 border-zinc-600 bg-transparent text-[#b6ff33] focus:ring-[#b6ff33]" type="radio" name="category" value="{{ $category->slug }}" @checked(request('category') === $category->slug)><span>{{ $category->name }}</span></label>@endforeach<label class="flex cursor-pointer items-center gap-3 text-sm text-zinc-300"><input class="size-4 border-zinc-600 bg-transparent text-[#b6ff33] focus:ring-[#b6ff33]" type="radio" name="category" value="" @checked(! request('category'))><span>Tutte le categorie</span></label></div></fieldset>
                    <fieldset><legend class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400">Prezzo</legend><div class="mt-3 grid grid-cols-2 gap-3"><div><label class="sr-only" for="min_price">Prezzo minimo</label><input id="min_price" name="min_price" value="{{ request('min_price') }}" min="0" inputmode="decimal" class="w-full border border-white/15 bg-transparent px-3 py-3 text-sm focus:border-[#b6ff33] focus:outline-none" placeholder="Da €"></div><div><label class="sr-only" for="max_price">Prezzo massimo</label><input id="max_price" name="max_price" value="{{ request('max_price') }}" min="0" inputmode="decimal" class="w-full border border-white/15 bg-transparent px-3 py-3 text-sm focus:border-[#b6ff33] focus:outline-none" placeholder="A €"></div></div></fieldset>
                    <label class="flex cursor-pointer items-center gap-3 text-sm text-zinc-300"><input class="size-4 rounded border-zinc-600 bg-transparent text-[#b6ff33] focus:ring-[#b6ff33]" type="checkbox" name="in_stock" value="1" @checked(request()->boolean('in_stock'))><span>Solo disponibili</span></label>
                    <button class="w-full bg-[#b6ff33] px-4 py-3 text-xs font-black uppercase tracking-[0.14em] text-black transition hover:bg-white" type="submit">Applica filtri</button>
                    @if (request()->hasAny(['search', 'category', 'min_price', 'max_price', 'in_stock', 'sort']))<a class="block text-center text-[10px] font-bold uppercase tracking-[0.14em] text-zinc-400 hover:text-white" href="{{ route('catalog.index') }}">Azzera filtri</a>@endif
                </form>
            </aside>
            <section>
                <div class="mb-6 flex items-center justify-between gap-4"><p class="text-xs font-bold uppercase tracking-[0.14em] text-zinc-400">{{ $products->total() }} {{ $products->total() === 1 ? 'prodotto' : 'prodotti' }}</p><form method="GET" action="{{ route('catalog.index') }}"><input type="hidden" name="search" value="{{ request('search') }}"><input type="hidden" name="category" value="{{ request('category') }}"><input type="hidden" name="min_price" value="{{ request('min_price') }}"><input type="hidden" name="max_price" value="{{ request('max_price') }}">@if (request()->boolean('in_stock'))<input type="hidden" name="in_stock" value="1">@endif<label class="sr-only" for="sort">Ordina prodotti</label><select id="sort" name="sort" onchange="this.form.submit()" class="border-b border-white/20 bg-[#0a0a0a] pb-2 pr-8 text-xs font-bold uppercase tracking-[0.1em] text-white focus:border-[#b6ff33] focus:outline-none"><option value="latest" @selected(request('sort', 'latest') === 'latest')>Più recenti</option><option value="price_asc" @selected(request('sort') === 'price_asc')>Prezzo: crescente</option><option value="price_desc" @selected(request('sort') === 'price_desc')>Prezzo: decrescente</option></select></form></div>
                @if ($products->isNotEmpty())<div class="grid gap-x-4 gap-y-7 sm:grid-cols-2 xl:grid-cols-3">@foreach ($products as $product)<article class="group"><div class="relative aspect-[4/5] overflow-hidden {{ $loop->iteration % 3 === 1 ? 'bg-zinc-800' : ($loop->iteration % 3 === 2 ? 'bg-stone-800' : 'bg-neutral-700') }}"><span class="absolute left-4 top-4 text-[10px] font-black tracking-[0.18em] text-zinc-400">{{ $product->sku }}</span><div class="absolute inset-0 transition duration-500 group-hover:scale-105 {{ $loop->iteration % 3 === 1 ? 'bg-[radial-gradient(ellipse_at_center,rgba(182,255,51,0.3),transparent_60%)]' : '' }}"></div><div class="absolute bottom-0 left-1/2 h-[62%] w-[55%] -translate-x-1/2 rounded-t-[45%] bg-zinc-950"></div>@if ($product->stock <= 0)<span class="absolute bottom-4 left-4 bg-zinc-100 px-3 py-2 text-[10px] font-black uppercase tracking-wider text-black">Esaurito</span>@endif<a class="absolute inset-0" href="{{ route('products.show', $product) }}" aria-label="Vedi {{ $product->name }}"></a><span class="absolute bottom-4 right-4 grid size-10 place-items-center bg-[#b6ff33] text-lg text-black">→</span></div><div class="flex items-start justify-between gap-3 py-4"><div><p class="text-[10px] font-bold uppercase tracking-wider text-zinc-500">{{ $product->category->name }} / {{ $product->color }}</p><h2 class="mt-1 font-bold text-white"><a class="transition hover:text-[#b6ff33]" href="{{ route('products.show', $product) }}">{{ $product->name }}</a></h2></div><p class="text-sm font-bold text-[#b6ff33]">{{ number_format($product->price, 0, ',', '.') }} €</p></div></article>@endforeach</div><div class="mt-10">{{ $products->links() }}</div>@else<div class="border border-dashed border-white/20 px-6 py-16 text-center"><p class="text-lg font-black text-white">NESSUN PRODOTTO TROVATO.</p><p class="mt-2 text-sm text-zinc-400">Prova a cambiare o azzerare i filtri selezionati.</p><a class="mt-6 inline-block bg-[#b6ff33] px-5 py-3 text-xs font-black uppercase tracking-[0.14em] text-black" href="{{ route('catalog.index') }}">Mostra il catalogo</a></div>@endif
            </section>
        </div>
    </main>
    <footer class="border-t border-white/10 bg-[#0a0a0a] py-10"><div class="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-xs text-zinc-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><p class="text-xl font-black tracking-[-0.08em] text-white">URBAN<span class="text-[#b6ff33]">WEAR</span></p><p>© {{ date('Y') }} UrbanWear</p></div></footer>
</body>
</html>
