<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Checkout — UrbanWear</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#0a0a0a] font-sans text-zinc-100 antialiased">
    <div class="border-b border-white/10 bg-[#b6ff33] px-4 py-2 text-center text-[10px] font-black tracking-[0.2em] text-black sm:text-xs">SPEDIZIONE GRATUITA IN ITALIA SOPRA I 100 €</div>
    <header class="border-b border-white/10 bg-[#0a0a0a]/90"><nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><a href="{{ route('home') }}" class="text-xl font-black tracking-[-0.08em] text-white sm:text-2xl">URBAN<span class="text-[#b6ff33]">WEAR</span></a><a class="text-xs font-bold uppercase tracking-[0.14em] text-zinc-400 hover:text-white" href="{{ route('cart.index') }}">Torna al carrello</a></nav></header>
    <main class="mx-auto max-w-7xl px-5 py-12 lg:px-8 lg:py-16">
        <p class="text-[10px] font-black uppercase tracking-[0.24em] text-[#b6ff33]">UrbanWear / Checkout</p>
        <h1 class="mt-3 text-5xl font-black tracking-[-0.07em] text-white sm:text-7xl">CONCLUDI L’ORDINE.</h1>
        @if ($errors->any())<div class="mt-8 border border-red-400/40 bg-red-400/10 px-4 py-3 text-sm text-red-200">Controlla i dati inseriti e riprova.</div>@endif
        <form class="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]" action="{{ route('checkout.store') }}" method="POST">
            @csrf
            <section class="border-y border-white/10 py-6"><h2 class="text-xl font-black text-white">DATI DI CONSEGNA</h2><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="text-xs font-bold uppercase tracking-wider text-zinc-400 sm:col-span-2">Nome e cognome<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="customer_name" value="{{ old('customer_name') }}" required></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400">Email<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="customer_email" type="email" value="{{ old('customer_email') }}" required></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400">Telefono <span class="normal-case tracking-normal text-zinc-600">(opzionale)</span><input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="customer_phone" value="{{ old('customer_phone') }}"></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400 sm:col-span-2">Indirizzo<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="shipping_address" value="{{ old('shipping_address') }}" required></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400">Città<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="shipping_city" value="{{ old('shipping_city') }}" required></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400">CAP<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="shipping_postal_code" value="{{ old('shipping_postal_code') }}" required></label><label class="text-xs font-bold uppercase tracking-wider text-zinc-400 sm:col-span-2">Paese<input class="mt-2 w-full border border-white/20 bg-transparent px-4 py-3 text-sm text-white focus:border-[#b6ff33] focus:outline-none" name="shipping_country" value="{{ old('shipping_country', 'Italia') }}" required></label></div></section>
            <aside class="h-fit border border-white/15 bg-[#101010] p-6 lg:sticky lg:top-6"><h2 class="text-xl font-black text-white">RIEPILOGO</h2><div class="mt-6 space-y-3 border-b border-white/10 pb-5 text-sm text-zinc-400">@foreach ($items as $item)<div class="flex justify-between gap-4"><span>{{ $item['name'] }} × {{ $item['quantity'] }}</span><span>{{ number_format($item['price'] * $item['quantity'], 0, ',', '.') }} €</span></div>@endforeach</div><div class="mt-5 flex items-end justify-between"><span class="text-xs font-black uppercase tracking-wider text-white">Totale</span><span class="text-2xl font-black text-[#b6ff33]">{{ number_format($total, 0, ',', '.') }} €</span></div><button class="mt-7 w-full bg-[#b6ff33] px-4 py-4 text-xs font-black uppercase tracking-[0.14em] text-black transition hover:bg-white" type="submit">Conferma ordine</button></aside>
        </form>
    </main>
</body>
</html>
