<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ $product->name }} — UrbanWear.">
    <title>{{ $product->name }} — UrbanWear</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#0a0a0a] font-sans text-zinc-100 antialiased">
    <div class="border-b border-white/10 bg-[#b6ff33] px-4 py-2 text-center text-[10px] font-black tracking-[0.2em] text-black sm:text-xs">SPEDIZIONE GRATUITA IN ITALIA SOPRA I 100 €</div>
    <header class="border-b border-white/10 bg-[#0a0a0a]/90 backdrop-blur"><nav class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><a href="{{ route('home') }}" class="text-xl font-black tracking-[-0.08em] text-white sm:text-2xl">URBAN<span class="text-[#b6ff33]">WEAR</span></a><div class="hidden items-center gap-8 text-xs font-bold uppercase tracking-[0.16em] text-zinc-300 lg:flex"><a class="transition hover:text-[#b6ff33]" href="{{ route('home') }}#drop">Nuovi arrivi</a><a class="transition hover:text-[#b6ff33]" href="{{ route('catalog.index') }}">Shop</a><a class="transition hover:text-[#b6ff33]" href="{{ route('home') }}#story">Manifesto</a></div><a class="relative text-zinc-300 transition hover:text-[#b6ff33]" href="{{ route('cart.index') }}" aria-label="Apri il carrello"><svg class="size-5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 3h2l2.4 12.1a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 2-1.6L21 7H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg><span class="absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-[#b6ff33] text-[9px] font-black text-black">{{ collect(session('cart', []))->sum('quantity') }}</span></a></nav></header>
    <main class="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12">
        <a href="{{ route('catalog.index') }}" class="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.16em] text-zinc-400 transition hover:text-[#b6ff33]">← Torna al catalogo</a>
        @if (session('success'))<div class="mt-6 border border-[#b6ff33]/40 bg-[#b6ff33]/10 px-4 py-3 text-sm text-[#d5ff8c]" role="status">{{ session('success') }}</div>@endif
        <div class="mt-8 grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:gap-16">
            <section class="relative aspect-[4/5] overflow-hidden bg-zinc-800"><div class="absolute inset-0 bg-[linear-gradient(135deg,transparent_49.8%,rgba(182,255,51,0.7)_50%,transparent_50.2%)] opacity-20"></div><div class="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(182,255,51,0.28),transparent_60%)]"></div><div class="absolute bottom-0 left-1/2 h-[73%] w-[58%] -translate-x-1/2 rounded-t-[45%] bg-zinc-950 shadow-[0_0_0_1px_rgba(255,255,255,0.13)]"></div><div class="absolute left-[28%] top-[39%] w-[44%] border-y border-white/15 py-3 text-center text-[10px] font-black tracking-[0.24em] text-[#b6ff33]">{{ strtoupper(str_replace(' ', '_', $product->sku)) }}</div><p class="absolute bottom-5 left-5 text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400">{{ $product->color }} / Studio 2026</p></section>
            <section class="flex flex-col lg:py-4"><p class="text-[10px] font-black uppercase tracking-[0.2em] text-[#b6ff33]">{{ $product->category->name }} / {{ $product->sku }}</p><h1 class="mt-4 text-5xl font-black leading-[0.9] tracking-[-0.07em] text-white sm:text-6xl">{{ strtoupper($product->name) }}</h1><p class="mt-5 text-2xl font-black text-[#b6ff33]">{{ number_format($product->price, 0, ',', '.') }} €</p><p class="mt-8 max-w-xl text-sm leading-7 text-zinc-400">{{ $product->description }}</p><div class="mt-8 border-y border-white/10 py-5 text-xs text-zinc-400"><div class="flex justify-between"><span>Colore</span><span class="font-bold text-white">{{ $product->color }}</span></div><div class="mt-3 flex justify-between"><span>Disponibilità</span><span class="font-bold {{ $product->stock > 0 ? 'text-[#b6ff33]' : 'text-red-400' }}">{{ $product->stock > 0 ? $product->stock.' disponibili' : 'Esaurito' }}</span></div></div>
            <form id="add-to-cart" class="mt-8" action="{{ route('cart.store', $product) }}" method="POST">@csrf
                <fieldset><legend class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400">Scegli la taglia</legend><div class="mt-3 flex flex-wrap gap-2">@foreach ($product->sizes ?? [] as $size)<label><input class="peer sr-only" type="radio" name="size" value="{{ $size }}" @checked(old('size') === $size)><span class="grid min-w-12 cursor-pointer place-items-center border border-white/20 px-4 py-3 text-xs font-bold text-zinc-300 transition peer-checked:border-[#b6ff33] peer-checked:bg-[#b6ff33] peer-checked:text-black hover:border-white">{{ $size }}</span></label>@endforeach</div>@error('size')<p class="mt-2 text-xs text-red-400">{{ $message }}</p>@enderror</fieldset>
                <div class="mt-7 flex gap-3"><div><label class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-400" for="quantity">Quantità</label><input id="quantity" name="quantity" type="number" min="1" max="{{ $product->stock }}" value="{{ old('quantity', 1) }}" class="mt-3 block w-24 border border-white/20 bg-transparent px-3 py-4 text-sm text-white focus:border-[#b6ff33] focus:outline-none" @disabled($product->stock <= 0)></div><button class="mt-auto flex-1 bg-[#b6ff33] px-6 py-4 text-xs font-black uppercase tracking-[0.14em] text-black transition hover:bg-white disabled:cursor-not-allowed disabled:bg-zinc-700 disabled:text-zinc-400" type="submit" @disabled($product->stock <= 0)>{{ $product->stock > 0 ? 'Aggiungi al carrello' : 'Prodotto esaurito' }}</button></div>@error('quantity')<p class="mt-2 text-xs text-red-400">{{ $message }}</p>@enderror
            </form>
            </section>
        </div>
        @if ($relatedProducts->isNotEmpty())<section class="mt-20 border-t border-white/10 pt-12"><div class="flex items-end justify-between"><div><p class="text-[10px] font-black uppercase tracking-[0.2em] text-[#b6ff33]">Della stessa categoria</p><h2 class="mt-3 text-3xl font-black tracking-[-0.06em] text-white">POTREBBE PIACERTI.</h2></div><a href="{{ route('catalog.index', ['category' => $product->category->slug]) }}" class="hidden text-[10px] font-black uppercase tracking-[0.14em] text-zinc-400 hover:text-white sm:block">Vedi categoria →</a></div><div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach ($relatedProducts as $relatedProduct)<a class="group" href="{{ route('products.show', $relatedProduct) }}"><div class="relative aspect-[4/5] overflow-hidden bg-zinc-800"><div class="absolute inset-0 transition duration-500 group-hover:scale-105 group-hover:bg-[radial-gradient(ellipse_at_center,rgba(182,255,51,0.25),transparent_60%)]"></div><div class="absolute bottom-0 left-1/2 h-[62%] w-[55%] -translate-x-1/2 rounded-t-[45%] bg-zinc-950"></div></div><div class="flex justify-between gap-3 py-4"><div><p class="text-[10px] font-bold uppercase tracking-wider text-zinc-500">{{ $relatedProduct->color }}</p><h3 class="mt-1 font-bold text-white">{{ $relatedProduct->name }}</h3></div><p class="text-sm font-bold text-[#b6ff33]">{{ number_format($relatedProduct->price, 0, ',', '.') }} €</p></div></a>@endforeach</div></section>@endif
    </main>
</body>
</html>
